spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    open-in-view: false

    properties:
      hibernate:
        format_sql: true