spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: my-super-secret-key-for-project-management-platform-2026
  expiration: 3600000 #60m * 60s * 10000ms - 1 hour